export const daysInMonth = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
export const monthNames = [
  'JANUARY',
  'FEBRUARY',
  'MARCH',
  'APRIL',
  'MAY',
  'JUNE',
  'JULY',
  'AUGUST',
  'SEPTEMBER',
  'OCTOBER',
  'NOVEMBER',
  'DECEMBER',
];

export const phaseStyles = [
  { class: 'style17', text: 'Sprint - Planning' },
  { class: 'style19', text: 'Development - Coding' },
  { class: 'style20', text: 'Development - Sprint Testing' },
  { class: 'style21', text: 'Development - Code Integration' },
  { class: 'style22', text: 'Development - Integration Testing' },
  { class: 'style23', text: 'PPRFIX - Performance (Dev, SRE)' },
  { class: 'style24', text: 'PPR - Golden Data' },
  { class: 'style25', text: 'PPR - Regression' },
  { class: 'style26', text: 'UAT' },
  { class: 'style27', text: 'Release - Go/No Go' },
  { class: 'style28', text: 'Release - Rollout Plan' },
  { class: 'style29', text: 'Release - Beta Testing' },
  { class: 'style30', text: 'Release - Go Live' },
  { class: 'style31', text: 'Sprint - Review' },
  { class: 'style32', text: 'Sprint - Retrospective' },
];

export const newAppPhaseStyles = [
  { class: 'style19', text: 'Development . JM' },
  { class: 'style40', text: 'Development - Integration Testing' },
  { class: 'style41', text: 'Code Integration' },
  { class: 'style23', text: 'QA - Performance (Dev, SRE)' },
  { class: 'style24', text: 'QA - Golden Data' },
  { class: 'style42', text: 'QA - Analytics Regression' },
  { class: 'style25', text: 'QA - Regression' },
  { class: 'style26', text: 'UAT' },
  { class: 'style27', text: 'Release - Go/No Go' },
  { class: 'style28', text: 'Release - Rollout Plan' },
  { class: 'style43', text: 'Release - Beta Testing' },
  { class: 'style30', text: 'Release - Go Live' },
  { class: 'style31', text: 'Sprint - Review' },
  { class: 'style32', text: 'Sprint - Retrospective' },
];
